### ISSUE TITLE
How to use in a TypeScript project

### ISSUE THREAD

**Issue by simon-johansson** [GameAnalytics/GA-SDK-JAVASCRIPT#34]
When I try to import the lib in a TypeScript project like so:

```
import gameanalytics from 'gameanalytics';
```

 I get the following error `'GameAnalytics.d.ts' is not a module`. I guess this is because `GameAnalytics.d.ts` does not export anything. If I add `export default gameanalytics;` to the bottom of the `GameAnalytics.d.ts` I can use the lib as expected. Is there a reason for not exporting anything from that file?

**Comment by the1schwartz** [comment]
Yeah that is a mistake. That has been fixed now in the latest version (v3.1.1). Let me know if you still problems using it.

Use it like this:
import GameAnalytics from 'gameanalytics';

**Comment by simon-johansson** [comment]
Thank you for the quick reply! 

But I still get the same problem. It does not look like there were any changes made to the typescript definition file in the dist folder for the v3.1.1 release.

**Comment by the1schwartz** [comment]
Ah yeah I can see. I think the release script apparently overwrote the changes I made.

I will fix this now.

**Comment by the1schwartz** [comment]
Try updating again. Now the declaration file should be fixed in the latest version.
